planning_scene_monitor_options:
  name: planning_scene_monitor
  robot_description: robot_description
  joint_state_topic: /joint_states
  attached_collision_object_topic: /planning_scene_monitor
  publish_planning_scene_topic: /publish_planning_scene
  monitored_planning_scene_topic: /monitored_planning_scene
  wait_for_initial_state_timeout: 10.0

planning_pipelines:
  #namespace: "moveit_cpp"  # optional, default is ~
  pipeline_names: ["ompl"]
ompl:
  planning_plugin: ompl_interface/OMPLPlanner
  planning_plugins:
    - ompl_interface/OMPLPlanner

plan_request_params:
  planning_pipeline: ompl
  planning_plugins:
    - ompl_interface/OMPLPlanner
  planning_time: 5.0
  planning_attempts: 3
  max_velocity_scaling_factor: 0.5
  max_acceleration_scaling_factor: 0.5


  request_adapters:
    - "default_planning_request_adapters/AddTimeOptimalParameterization"
    - "default_planning_request_adapters/FixWorkspaceBounds"
    - "default_planning_request_adapters/FixStartStateBounds"
    - "default_planning_request_adapters/FixStartStateCollision"
    - "default_planning_request_adapters/FixStartStatePathConstraints"
  start_state_max_bounds_error: 0.1


planner_configs:
  # Global planner configurations
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0

igus_rebel_arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault